
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardSpritePath : Luban.BeanBase
{
    public CardSpritePath(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["CardType"].IsNumber) { throw new SerializationException(); }  CardType = (CardTypeConfig.CardTypeEnum)_buf["CardType"].AsInt; }
        { if(!_buf["SpriteAtlasPath"].IsString) { throw new SerializationException(); }  SpriteAtlasPath = _buf["SpriteAtlasPath"]; }
    }

    public static CardSpritePath DeserializeCardSpritePath(JSONNode _buf)
    {
        return new CardSpritePath(_buf);
    }

    public readonly int Id;
    public readonly CardTypeConfig.CardTypeEnum CardType;
    public readonly string SpriteAtlasPath;
   
    public const int __ID__ = -448888870;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "CardType:" + CardType + ","
        + "SpriteAtlasPath:" + SpriteAtlasPath + ","
        + "}";
    }
}

}
