
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.CardTypeConfig
{ 
    [System.Flags]
    public enum CardTypeEnum
    {
        /// <summary>
        /// 士兵
        /// </summary>
        SUMMON = 1,
        /// <summary>
        /// 装备
        /// </summary>
        EQUIPMENT = 2,
        /// <summary>
        /// 魔法
        /// </summary>
        MAGIC = 3,
    }

} 

