
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ElemTypeTable
{
public partial class TbElemTypePrefab
{
    private readonly System.Collections.Generic.Dictionary<int, ElemTypePrefab> _dataMap;
    private readonly System.Collections.Generic.List<ElemTypePrefab> _dataList;
    
    public TbElemTypePrefab(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ElemTypePrefab>();
        _dataList = new System.Collections.Generic.List<ElemTypePrefab>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ElemTypePrefab _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ElemTypePrefab.DeserializeElemTypePrefab(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ElemTypePrefab> DataMap => _dataMap;
    public System.Collections.Generic.List<ElemTypePrefab> DataList => _dataList;

    public ElemTypePrefab GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ElemTypePrefab Get(int key) => _dataMap[key];
    public ElemTypePrefab this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
