
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ElemTypeConfig
{ 
    [System.Flags]
    public enum ElemTypeEnum
    {
        /// <summary>
        /// 地
        /// </summary>
        WIND = 1,
        /// <summary>
        /// 风
        /// </summary>
        GRASS = 2,
        /// <summary>
        /// 水
        /// </summary>
        WATER = 3,
        /// <summary>
        /// 火
        /// </summary>
        FIRE = 4,
        /// <summary>
        /// 岩
        /// </summary>
        ROCK = 5,
    }

} 

