
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ElemCardTable
{
public partial class TbCardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, CardConfig> _dataMap;
    private readonly System.Collections.Generic.List<CardConfig> _dataList;
    
    public TbCardConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CardConfig>();
        _dataList = new System.Collections.Generic.List<CardConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardConfig.DeserializeCardConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<CardConfig> DataList => _dataList;

    public CardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardConfig Get(int key) => _dataMap[key];
    public CardConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
