
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SpritePath
{
public partial class TbCardSpritePath
{
    private readonly System.Collections.Generic.Dictionary<int, CardSpritePath> _dataMap;
    private readonly System.Collections.Generic.List<CardSpritePath> _dataList;
    
    public TbCardSpritePath(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CardSpritePath>();
        _dataList = new System.Collections.Generic.List<CardSpritePath>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardSpritePath _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardSpritePath.DeserializeCardSpritePath(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CardSpritePath> DataMap => _dataMap;
    public System.Collections.Generic.List<CardSpritePath> DataList => _dataList;

    public CardSpritePath GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardSpritePath Get(int key) => _dataMap[key];
    public CardSpritePath this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
