
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public ElemCardTable.TbCardConfig TbCardConfig {get; }
    public ElemTypeTable.TbElemTypePrefab TbElemTypePrefab {get; }
    public SpritePath.TbCardSpritePath TbCardSpritePath {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCardConfig = new ElemCardTable.TbCardConfig(loader("elemcardtable_tbcardconfig"));
        TbElemTypePrefab = new ElemTypeTable.TbElemTypePrefab(loader("elemtypetable_tbelemtypeprefab"));
        TbCardSpritePath = new SpritePath.TbCardSpritePath(loader("spritepath_tbcardspritepath"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCardConfig.ResolveRef(this);
        TbElemTypePrefab.ResolveRef(this);
        TbCardSpritePath.ResolveRef(this);
    }
}

}
